#!/bin/sh

#
# This script computes the various flags needed to run GNU C++ testsuites
# (compiler specific as well as library specific). 
#
# Written by Benjamin Kosnik <bkoz@redhat.com>
#            Gabriel Dos Reis <gdr@codesourcery.com>
#

# Print a message saying how this script is intended to be invoked
print_usage() {
    cat <<EOF
Usage: 
    testsuite_flags --install-includes
		    --build-includes
		    --build-cxx
		    --build-cc
		    --install-cxx
		    --cxxflags
		    --cxxpchflags
		    --cxxldflags
EOF
}

# Establish configure-generated directory structure.
BUILD_DIR=/Users/folsson/Downloads/gcc-mint/m68k-atari-mint/m68020-60/libstdc++-v3
SRC_DIR=/Users/folsson/Downloads/gcc-4.6.4/libstdc++-v3
PREFIX_DIR=/opt/cross-mint
query=$1

case ${query} in
    --install-includes)
      INCLUDES="-I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --build-includes)
      INCLUDES="-nostdinc++ -I/Users/folsson/Downloads/gcc-mint/m68k-atari-mint/m68020-60/libstdc++-v3/include/m68k-atari-mint -I/Users/folsson/Downloads/gcc-mint/m68k-atari-mint/m68020-60/libstdc++-v3/include -I/Users/folsson/Downloads/gcc-4.6.4/libstdc++-v3/libsupc++ 
                -I${SRC_DIR}/include/backward -I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --install-cxx)
      CXX=${PREFIX_DIR}/bin/g++
      echo ${CXX}
      ;;
    --build-cxx)
      CXX_build="/Users/folsson/Downloads/gcc-mint/./gcc/xgcc -shared-libgcc -B/Users/folsson/Downloads/gcc-mint/./gcc -nostdinc++ -L/Users/folsson/Downloads/gcc-mint/m68k-atari-mint/m68020-60/libstdc++-v3/src -L/Users/folsson/Downloads/gcc-mint/m68k-atari-mint/m68020-60/libstdc++-v3/src/.libs -B/opt/cross-mint/m68k-atari-mint/bin/ -B/opt/cross-mint/m68k-atari-mint/lib/ -isystem /opt/cross-mint/m68k-atari-mint/include -isystem /opt/cross-mint/m68k-atari-mint/sys-include  -m68020-60"
      CXX=`echo "$CXX_build" | sed 's,gcc/xgcc ,gcc/g++ ,'`
      echo ${CXX}
      ;;
    --build-cc)
      CC_build="/Users/folsson/Downloads/gcc-mint/./gcc/xgcc -B/Users/folsson/Downloads/gcc-mint/./gcc/ -B/opt/cross-mint/m68k-atari-mint/bin/ -B/opt/cross-mint/m68k-atari-mint/lib/ -isystem /opt/cross-mint/m68k-atari-mint/include -isystem /opt/cross-mint/m68k-atari-mint/sys-include  -m68020-60"
      CC="$CC_build"
      echo ${CC}
      ;;
    --cxxflags)
      CXXFLAGS_default="-g -O2 -D_GLIBCXX_ASSERT -fmessage-length=0"
      CXXFLAGS_config=" -D_GNU_SOURCE -g -O2 "
      echo ${CXXFLAGS_default} ${CXXFLAGS_config}
      ;;
    --cxxparallelflags)
      CXXFLAGS_parallel="-D_GLIBCXX_PARALLEL -fopenmp
			 -B${BUILD_DIR}/../libgomp 
                         -I${BUILD_DIR}/../libgomp 
			 -L${BUILD_DIR}/../libgomp/.libs -lgomp"
      echo ${CXXFLAGS_parallel}
      ;;
    --cxxpchflags)
      PCHFLAGS=""
      echo ${PCHFLAGS}
      ;;
    --cxxldflags)
      SECTIONLDFLAGS="-Wl,--gc-sections  "
      echo ${SECTIONLDFLAGS}
      ;;
    *)
      print_usage
      ;;
esac

exit 0
